### ISSUE TITLE
Cannot read property 'pkg' of null

### ISSUE THREAD

**Issue by wanshun888** [szimek/webrtc-translate#13]
When I try to run this with ember I get the following:

Cannot read property 'pkg' of null
TypeError: Cannot read property 'pkg' of null
    at Function.Addon.resolvePath (C:\project\node_modules\ember-cli\lib\models\addon.js:251:18)
    at Function.Addon.lookup (C:\project\node_modules\ember-cli\lib\models\addon.js:266:22)
    at C:\project\node_modules\ember-cli\lib\models\project.js:153:34
    at visit (C:\project\node_modules\ember-cli\lib\utilities\DAG.js:23:3)
    at DAG.topsort (C:\project\node_modules\ember-cli\lib\utilities\DAG.js:82:7)
    at Project.initializeAddons (C:\project\node_modules\ember-cli\lib\models\project.js:151:9)
    at Project.eachAddonCommand (C:\project\node_modules\ember-cli\lib\models\project.js:176:10)
    at module.exports (C:\project\node_modules\ember-cli\lib\cli\lookup-command.js:52:13)
    at CLI.<anonymous> (C:\project\node_modules\ember-cli\lib\cli\cli.js:31:26)
    at $$$internal$$tryCatch (C:\project\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:470:16)

**Comment by wanshun888** [comment]
I am using the latest ember version (0.0.44)

**Comment by szimek** [comment]
I haven't touch this project in a long time, but I've just tried to set it up and surprisingly it worked fine.

Make sure you're using node 6.x and not the latest 7.x version. After you clone it, run `bower install && npm install`. Then run `GOOGLE_TRANSLATE_API_KEY=XXXXXX ./node_modules/.bin/ember server` - this will ensure that you're running the local version of ember command and not a global one, which might be a different version.

**Comment by wanshun888** [comment]
I've got it working (issue seems to be I was running `ember server` from the webrtc-translate directory instead of in .bin)
